# This is a basic workflow to help you get started with Actions

name: Terraform Plan

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  Terraform-Plan:
    #Defining Azure Environment Secrets
    env:
      ARM_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
    environment: production
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v1
              
      # Checks that all Terraform configuration files adhere to a canonical format
      - name: 'Terraform Format'
        run:   terraform fmt -recursive
      
      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.   
      - name: 'Terraform Init'
        run:   terraform init
        
      # Import Terraform HP Pool into Configuration
      - name: 'Terraform Import'
        run:   terraform import azurerm_virtual_desktop_host_pool.hp "/subscriptions/5cf4abf5-ed25-4111-af57-8157f704166e/resourceGroups/avdazhprgeas/providers/Microsoft.DesktopVirtualization/hostPools/HP-STD-PROD-SAP-Desktop-EAS"
      
      # Validate Terraform Configuration & State File
      - name: 'Terraform Validate'
        run:   terraform validate -no-color

      # Generates an execution plan for Terraform   
      - name: 'Terraform Plan'
        run:   terraform plan -input=false -no-color -out=tfplan | tee terraform_plan.log

      - name: Upload Plan Log as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-log
          path: terraform_plan.log

      - name: Upload Terraform Plan File as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan
