# This is a basic workflow to help you get started with Actions

name: Terraform Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  Terraform-Build:
    #Defining Azure Environment Secrets
    env:
      ARM_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
    environment: production
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v1
              
      # Checks that all Terraform configuration files adhere to a canonical format
      - name: 'Terraform Format'
        run:   terraform fmt -recursive
      
      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.   
      - name: 'Terraform Init'
        run:   terraform init
      
      # Validate Terraform Configuration & State File
      - name: 'Terraform Validate'
        run:   terraform validate -no-color

      # Generates an execution plan for Terraform   
      - name: 'Terraform Plan'
        run:   terraform plan -input=false

      # Create AVD Infra in Azure
      - name: 'Terraform Apply'
        run:   terraform apply -auto-approve -no-color
